---
- name: "Main | Include linux main task file"
  ansible.builtin.include_tasks:
    file: linux/main.yml
  when: ansible_connection == 'ssh'

- name: "Main | Include windows main task file"
  ansible.builtin.include_tasks:
    file: windows/main.yml
  when: ansible_connection == 'winrm'
...
