---
- name: "Main | Get date and time"
  ansible.builtin.set_fact:
    start_time: "{{ ansible_date_time.iso8601_basic_short }}"
  tags: always

- name: "Main | Include linux main task file"
  ansible.builtin.include_tasks:
    file: 'linux/main.yml'
  when: ansible_connection == 'ssh'
  tags: always

- name: "Main | Include windows main task file"
  ansible.builtin.include_tasks:
    file: 'windows/main.yml'
  when: ansible_connection == 'winrm'
  tags: always
...
