---
- name: "VMware Snapshot | Take Snapshot of VM"
  community.vmware.vmware_guest_snapshot:
    datacenter: '{{ vmware_guest_folder }}'
    folder: '{{ vmware_guest_folder }}'
    name: '{{ vmware_guest_name }}'
    state: present
    snapshot_name: "snapshot-{{ now(utc=false, fmt='%Y-%m-%d_%H-%M') }}"
    description: "snapshot-{{ now(utc=false, fmt='%Y-%m-%d_%H-%M') }}"
  delegate_to: localhost
  become: false
...
