---
- name: "Windows | Main | Get date and time"
  ansible.builtin.set_fact:
    start_time: "{{ ansible_date_time.iso8601_basic_short }}"

- name: Check for Available Updates
  ansible.builtin.import_tasks:
    file: windows/available_updates.yml

- name: Patch Servers
  when: (__updatable_packages is defined and __updatable_packages | length > 0)
  block:

    - name: Patch Servers
      ansible.builtin.import_tasks:
        file: windows/patching.yml

    - name: Archive logs
      ansible.builtin.import_tasks:
        file: windows/postupgrade.yml
...
