---
- name: "Windows | Patching | Install updatable Packages"
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    skip_optional: true
    state: installed
    reject_list: '{{ role_patching_all__windows_reject_list | default(omit) }}'
  failed_when: false
  no_log: true
...
