---
- name: "Windows | Post Upgrade | Archive logs"
  community.windows.win_zip:
    src: "{{ role_patching_all__windows_patching_temp_dir }}\\{{ inventory_hostname }}_patching"
    dest: "{{ role_patching_all__windows_patching_logs_storage }}\\{{ inventory_hostname }}\\{{ inventory_hostname }}-{{ start_time }}-patching-logs.zip"
  delegate_to: '{{ role_patching_all__windows_storage_server }}'

- name: Windows | Post Upgrade | Clean up temp dir"
  ansible.windows.win_file:
    path: "{{ role_patching_all__windows_patching_temp_dir }}\\{{ inventory_hostname }}_patching"
    state: absent
  delegate_to: '{{ role_patching_all__windows_storage_server }}'
...
