---
- name: "Linux | Main | Get date and time"
  ansible.builtin.set_fact:
    start_time: "{{ ansible_date_time.iso8601_basic_short }}"

- name: "Linux | Main | Check for Available Updates"
  ansible.builtin.include_tasks:
    file: linux/available_updates.yml

- name: "Linux | Main | Patch Servers Block"
  when: (__updatable_packages is defined and __updatable_packages | length > 0 )
  block:

    - name: "Linux | Main | Get Current Packages"
      ansible.builtin.include_tasks:
        file: linux/current_packages.yml

    - name: "Linux | Main | Patch Servers"
      ansible.builtin.include_tasks:
        file: linux/patching.yml

    - name: "Linux | Main | Archive logs"
      ansible.builtin.include_tasks:
        file: linux/postupgrade_packages.yml
...
