---
- name: "Linux | Main | Get date and time"
  ansible.builtin.set_fact:
    start_time: "{{ ansible_date_time.iso8601_basic_short }}"

- name: "Linux | Main | Check for Available Updates"
  ansible.builtin.include_tasks:
    file: linux/available_updates.yml
  tags: always

- name: "Linux | Main | Patch Servers Block"
  when: (__updatable_packages is defined and __updatable_packages | length > 0 )
  tags: patch
  block:

    - name: "Linux | Main | Include Current Packages Tasks File"
      ansible.builtin.include_tasks:
        file: linux/current_packages.yml

    - name: "Linux | Main | Include VMware Snapshot Tasks File"
      ansible.builtin.include_tasks:
        file: vmware_snapshot.yml
      when: vmware_guest_name is defined

    - name: "Linux | Main | Include Patching Tasks File"
      ansible.builtin.include_tasks:
        file: linux/patching.yml

    - name: "Linux | Main | Include Post Upgrade Tasks File"
      ansible.builtin.include_tasks:
        file: linux/postupgrade_packages.yml
...
