---
- name: "Linux | Patching | Ubuntu/Debian Block"
  when: ansible_distribution is match (Ubuntu|Debian)
  block:
    - name: "Linux | Patching | Perform upgrade | Ubuntu/Debian"
      ansible.builtin.apt:
        state: latest
        dpkg_options: 'force-confdef'
        update_cache: true
        only_upgrade: true
        upgrade: '{% if role_patching__dist_upgrade | bool %}dist{% else %}yes{% endif %}'
      register: __perform_upgrade
      # changed_when: __perform_upgrade.rc != 0
      # no_log: true

    - name: "Linux | Patching | Apt autoremove | Ubuntu/Debian"
      ansible.builtin.apt:
        autoremove: true
      no_log: true

- name: "Linux | Patching | CentOS"
  when: ansible_distribution == "CentOS"
  block:
    - name: Perform upgrade | CentOS
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
        update_only: true
      register: __perform_upgrade
      # changed_when: __perform_upgrade != 0
      no_log: true

    - name: "Linux | Patching | Autoremove | CentOS"
      ansible.builtin.dnf:
        autoremove: true
      # no_log: true
...
